[tools]
rust = "1.95"
zig = "latest"
upx = "latest"
uv = "latest"
jq = "latest"
yq = "latest"
hyperfine = "latest"
vhs = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-outdated" = "latest"
